---
- name: Setup Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: ./output_vars

    - name: Import stack setup Variable
      include_vars: ./stack_setup
      
    - name: Create sample ec2 key
      ec2_key:
        name: sample
        region: "{{region}}"
      register: samplekey_out
      
    - name: Save private key into file sample-key.pem
      copy:
        content: "{{samplekey_out.key.private_key}}"
        dest: "./sample.pem"
        mode: 0600
      when: samplekey_out.changed 
      
    - name: Create Securiry Group for Load Balancer
      ec2_group:
        name: ec2ELB-sg
        description: Allow port 80 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: ec2ELBSG_out
      
    - name: Create Securiry Group for Ec2 Stack
      ec2_group:
        name: ec2Stack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ec2ELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: ec2StackSG_out
      
    - name: Update Securiry Group with its own sg id
      ec2_group:
        name: ec2Stack-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ec2StackSG_out.group_id}}"
            
    - name: Creating Nginx web01
      ec2_instance:
        key_name: sample
        region: "{{region}}"
        instance_type: t2.micro
        image_i: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 120
        tags:
          Name: "web01"
          Project: Bharath
          Owner: DevOps Team
        network:
          security_group: "{{ec2StackSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: web01_out 
      
    - name: Creating tomcat app01
      ec2_instance:
        key_name: sample
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 120
        tags:
          Name: "app01"
          Project: Bharath
          Owner: DevOps Team
        network:
          security_group: "{{ec2StackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    - name: Creating memcache mc01
      ec2_instance:
        key_name: sample
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 120
        tags:
          Name: "mc01"
          Project: Bharath
          Owner: DevOps Team
        network:
          security_group: "{{ec2StackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

    - name: Creating RabbitMQ rmq01
      ec2_instance:
        key_name: sample
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{rmq_ami}}"
        wait: yes
        wait_timeout: 120
        tags:
          Name: "rmq01"
          Project: Bharath
          Owner: DevOps Team
        network:
          security_group: "{{ec2StackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: rmq01_out

    - name: Creating Mysql db01
      ec2_instance:
        key_name: sample
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 120
        tags:
          Name: "db01"
          Project: Bharath
          Owner: DevOps Team
        network:
          security_group: "{{ec2StackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out.tagged_instances[0].id
     
    - local_action:
        module: ec2_elb_lb
        name: "ec2-elb"
        region: "{{region}}"
        state: present
        instance_ids:
          - "{{ web01_out.tagged_instances[0].id }}"
        purge_instance_ids: true
        security_group_ids: "{{ ec2ELBSG_out.group_id }}"
        subnets:
          - "{{ pubsub1id }}"
          - "{{ pubsub2id }}"
          - "{{ pubsub3id }}"
        listeners:
          - protocol: http # options are http, https, ssl, tcp
            load_balancer_port: 80
            instance_port: 80
       
    - name: Insert/Update Hosts IP & Name in file provision-stack/group_vars/hostsip
      blockinfile:
        path: provision-stack/group_vars/hostsip
        block: |
          web01_ip: {{ web01_out.tagged_instances[0].private_ip }}
          app01_ip: {{ app01_out.tagged_instances[0].private_ip }}
          rmq01_ip: {{ rmq01_out.tagged_instances[0].private_ip }}
          mc01_ip: {{ mc01_out.tagged_instances[0].private_ip }}
          db01_ip: {{ db01_out.tagged_instances[0].private_ip }}
    
    - name: Copy sample key to provision_stack directory
      copy:
        src: sample.pem
        dest: provision-stack/sample.pem
        mode: '0400'

    - name: Insert/Update Inventory file provision-stack/inventory-Bharath
      blockinfile:
        path: provision-stack/inventory-Bharath
        block: |
          web01 ansible_host={{ web01_out.tagged_instances[0].private_ip }}
          app01 ansible_host={{ app01_out.tagged_instances[0].private_ip }}
          rmq01 ansible_host={{ rmq01_out.tagged_instances[0].private_ip }}
          mc01 ansible_host={{ mc01_out.tagged_instances[0].private_ip }}
          db01 ansible_host={{ db01_out.tagged_instances[0].private_ip }}
          cntl ansible_host=127.0.0.1 ansible_connection=local
          
          [websrvgrp]
          web01
          
          [appsrvgrp]
          app01
          
          [rmqsrvgrp]
          rmq01
          
          [mcsrvgrp]
          mc01
          
          [dbsrvgrp]
          db01
          
          [control]
          cntl 
          
          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp
          
          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=sample.pem
          #ansible_python_interpreter=/usr/bin/python3
      
